# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MtTVKuYXSNxneCQYNBRT2v9t8effS0T
"""

import streamlit as st
import torch
from transformers import T5ForConditionalGeneration, T5Tokenizer

# Load Model
model = T5ForConditionalGeneration.from_pretrained("t5-small")
tokenizer = T5Tokenizer.from_pretrained("t5-small")

# Streamlit UI
st.title("Machine Translation App")
text_input = st.text_input("Enter text to translate:")

if st.button("Translate"):
    input_text = f"translate English to French: {text_input}"
    inputs = tokenizer(input_text, return_tensors="pt")
    output = model.generate(**inputs)
    translated_text = tokenizer.decode(output[0], skip_special_tokens=True)
    st.write("Translation:", translated_text)